import type { Metadata } from "next";
import "./globals.css";
import { Dashboard } from "@/components/shared/dashboard";
import ThemeProvider from "@/components/shared/ThemeProvider";
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
  title: "KeplerBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>

        <ThemeProvider>

          <Header className="bg-[#EAEAEA] dark:bg-[#171717] fixed top-0 left-[270px] w-[calc(100%-270px)] z-[1000]" />

          <main className="grid grid-cols-[270px_1fr]">
            <Dashboard className="bg-[#EAEAEA] dark:bg-[#171717] z-[1000px]" />
            <div className="pt-[89px] ">
              {children}
            </div>
          </main>

        </ThemeProvider>

      </body>
    </html>
  );
}
